server:
  host: 0.0.0.0
  port: 8081
  mode: debug # debug, release, test
  allow_anonymous_debug: false
  shutdown_timeout_sec: 10
  cors:
    allow_origins:
      - http://localhost:5172
      - http://127.0.0.1:5172
    allow_credentials: true

mysql:
  host: 127.0.0.1
  port: 3306
  user: change_me
  password: change_me
  dbname: change_me
  config: charset=utf8mb4&parseTime=True&loc=Local

jwt:
  secret: change_me_put_real_secret_in_configs_config_local_yaml
