server:
  port: 8080
  mode: debug # debug, release, test

mysql:
  host: "database-1.cdsy6cgcuu1i.ap-southeast-2.rds.amazonaws.com"
  port: 3306
  user: "admin"
  password: "Eyhs6FNgnXFaOLuWX5uN"
  dbname: "tgvive"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "change_me"

telegram:
  api_id: 15055931
  api_hash: "021d433426cbb920eeb95164498fe3d3"
  session_path: "./sessions/"
