server:
  port: 8080
  mode: debug # debug, release, test

mysql:
  host: "142.171.85.117"
  port: 3306
  user: "revive"
  password: "HL8sJBz4kYPG8XFF"
  dbname: "revive"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "change_me"

telegram:
  api_id: 15055931
  api_hash: "021d433426cbb920eeb95164498fe3d3"
  session_path: "./sessions/"
